name: Daily Data Release

permissions:
  contents: write

on:
  schedule:
    - cron: "0 6 * * *" # runs every day at 06:00 UTC
  workflow_dispatch: # manual trigger if needed

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare download folder
        run: mkdir -p downloads

      - name: Download OpenCellID
        env:
          API_KEY: ${{ secrets.OPENCELLID }}
        run: |
          echo testing13 > downloads/test1

      - name: Download OSM Surveillance Camera
        run: |
          echo testing23 > downloads/test2

      - name: Publish rolling release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: daily-latest
          name: "Daily Dataset (latest)"
          body: "Automatically updated every day at 06:00 UTC."
          draft: false
          prerelease: false
          files: |
            downloads/test1
            downloads/test2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
